module.exports = {
  ADD_SUCCESS: 'ADD_SUCCESS',
  LIST_SUCCESS: 'LIST_SUCCESS',
  SET_LOADING: 'SET_LOADING',
  RESET_LOADING: 'RESET_LOADING',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
};
